name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
    - name: Install functional-tests/ dependencies
      run: npm ci
      working-directory: ./functional-tests
    - parallel:
      - name: Lint functional-tests/
        run: npm run lint
        working-directory: ./functional-tests
      - name: Format functional-tests/
        run: npm run format
        working-directory: ./functional-tests
      - name: Compile functional-tests/
        run: npx tsc
        working-directory: ./functional-tests
    - parallel:
      - name: Install app/ dependencies
        run: npm ci
        working-directory: ./app
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
        working-directory: ./functional-tests
    - parallel:
      - name: Lint app/
        run: npm run lint
        working-directory: ./app
      - name: Test app/
        run: npm test
        working-directory: ./app
    - name: Run Playwright tests
      run: npm test
      working-directory: ./functional-tests
    - uses: actions/upload-artifact@v7
      if: ${{ always() }}
      with:
        name: playwright-report
        path: ./functional-tests/playwright-report
        retention-days: 5
